In [2]:
import pandas as pd
df=pd.read_csv('music.csv')
df1=pd.read_excel('VideoGameDataset.xlsx')
df1.describe()

,vg_score,critic_score,user_score,total_shipped,aisan_sales,north_american_sales,japan_sales,european_sales,global_sales,release_year
count,13763.000000,13763.000000,13763.000000,13763.000000,13763.000000,13763.000000,13763.000000,13763.000000,13763.000000,13763.000000
mean,5.486253,5.715484,5.512303,143.891264,3.099876,2.722866,3.121373,3.128790,12.072904,2000.434716
std,2.871480,2.821842,2.870206,90.370429,2.588406,2.030969,1.737130,2.212131,5.804262,24.644377
min,1.000000,1.000000,0.130000,0.070000,0.010000,0.010000,0.010000,0.010000,0.090000,1900.000000
25%,3.000000,3.000000,3.000000,65.000000,0.390000,1.090000,1.770000,1.200000,7.060000,2000.000000
50%,5.000000,6.000000,5.000000,144.000000,2.770000,2.580000,3.170000,3.120000,12.980000,2007.000000
75%,8.000000,8.000000,8.000000,223.000000,5.340000,4.140000,4.620000,5.060000,16.600000,2010.000000
max,10.000000,10.000000,10.000000,300.000000,15.090000,8.000000,6.000000,8.640000,27.730000,2020.000000

In [8]:
df.shape
df1.shape

(13763, 14)

In [3]:
df

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [65]:
X = df1.drop(columns=['global_sales'])
Y = df1['global_sales']
X.columns

KeyError: "['global_sales'] not found in axis"

In [4]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib

X = df.drop(columns=['genre'])
Y = df['genre']
print(X.columns)

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2) # To seperate test dataset 

model = DecisionTreeClassifier() # Create model
model.fit(X_train,Y_train) # Fit input and output dataset in model

joblib.dump(model,'music-recc.joblib') # Store created model in new file

Index(['age', 'gender'], dtype='object')

['music-recc.joblib']

In [5]:
import joblib
model = joblib.load('music-recc.joblib')# load a stored model
magic = model.predict(X_test) # predict the response of model

print(magic)
score = accuracy_score(Y_test,magic) # check accuracy score between 0 and 1
score

['Classical' 'Dance' 'Acoustic' 'Acoustic']

1.0

In [6]:
from sklearn import tree

tree.export_graphviz(model,out_file='music.dot',
                     feature_names=['age', 'gender'],
                     class_names=sorted(Y.unique()),
                    label=True,filled=True)